bool imu_state
bool pressure_state
bool down_visual_state
bool gravity_state
bool wind_state
int32 drone_hover
int32 factory_mode
uint8 imu_calibration_state
uint8 fly_mode #1 Landed | 6 Flying
uint8 camera_state
uint8 electrical_machinery_state

bool front_in
bool front_out
bool front_lsc

bool power_state
bool battery_state
bool battery_low
bool battery_lower
int32 battery_percentage
int32 drone_battery_left

int32 light_strength

float32 fly_speed
float32 east_speed
float32 north_speed
float32 ground_speed
float32 fly_time
float32 drone_fly_time_left

int32 wifi_strength
int32 wifi_disturb

float32 height

float32 temperature_height
